### PR TITLE
WIP: move auto_publish_url from a Thread variable to inside the model

### PR DESCRIPTION
**Pull request by dougmartin**
This has not been tested yet - it was done during the 45 window we had in the Developer Retrospective.

### CODE REVIEW

**Comment by dougmartin** [comment]
I remember why the thread variable was used now.  The portal publication is queued automatically inside the model and it uses the request object to build the publishing url and the request object is not available in models in Rails.

**Comment by scytacki** [comment]
I think it would work if the 'auto_publish_url' was added to the PortalPublication model.  I believe the PortalPublication is created synchronously.  And also think it is OK to reuse the same URL on each auto publish. So this URL will be saved the very first time the material is published. That might result in some strange cases with the https/http issue. But I think it might be OK.

**Comment by dougmartin** [comment]
See my comment above yours - the reason I saved it in the thread at startup was the request object is not available in the model so it can't generate the url to save it in the model.  Look at all the breaking tests to see the problem in action.

**Comment by scytacki** [comment]
But in your code I think you are saving the url in the `PendingPortalPublication` not the `PortalPublication`.  I think the `PortalPublication` is always created synchronously from a controller.

**Comment by scytacki** [comment]
Here are a few places that create portal_publications:
https://github.com/concord-consortium/lara/blob/master/app/controllers/lightweight_activities_controller.rb#L194

https://github.com/concord-consortium/lara/blob/master/app/controllers/publications_controller.rb#L69

https://github.com/concord-consortium/lara/blob/master/app/controllers/import_controller.rb#L57

**Comment by dougmartin** [comment]
Three tests are failing but I'm out of time this iteration to work on tech debt so it will have to wait until next time.

**Comment by scytacki** [comment]
This last change of adding the auto_publish_url to activities and sequences won't work because the same activity or sequence can be published to two portals.

**Comment by scytacki** [comment]
Since I'm in this code. I'll summarize what I'm seeing and my current recommended solution.  So right now we make a new PortalPublication each time the material is updated.  The creation of this new publication happens in an `after_update` callback.  Because this is happening in the callback the only way we came up with to access the `auto_publish_url` was through the thread.

My recommendation is that we change how PortalPublication is used.  There would just be one of these for each combination of Portal and Material.  Then we use the PendingPortalPublication model (or a new one), to record information about each time the material is published.  It makes sense to say "the material is published to multiple portals".  Or "which portals is the material published to". So it makes sense that there is just one PortalPublication per portal.  The PendingPortalPublication would become more like a PortalPublicationEvent.  

An hacky intermediate step would be to use the initial PortalPublication that is created when Publishable#portal_publish is called to store the URL.  The portal_publish method seems to always be called from a controller, so it should be possible for these calls to directly pass the auto_publish_url.  Then when later re-publications performed this url they would look at the first PortalPublication of the material for this portal in order to get the url.

**Pull request closed without merging**
