### PR TITLE
Add redirects to image proxy [#98026438]

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by scytacki** [comment]
Instead of rolling our own redirect handler. Can you try using the HTTPParty gem:
http://johnnunemaker.com/httparty/

The gem is already included in LARA. Perhaps it will have issues handling the binary image bytes, but I think we should try to use it and find out.

**Comment by dougmartin** [comment]
@scytacki I updated it to use HTTPParty

**Comment by dougmartin** [comment]
Wait on this - it isn't sending the content type down correctly yet.

**Comment by dougmartin** [comment]
Ok, the content-type is being correctly sent.

**Comment by scytacki** [comment]
:+1:

**Pull request merged**
