### PR TITLE
[WIP] Added run serialization [#166063708]

### PR DESCRIPTION
**Pull request by dougmartin**
**NOTE**: this PR is based on the branch from this PR which should be merged first: https://github.com/concord-consortium/lara/pull/413

### CODE REVIEW

**Comment by dougmartin** [comment]
It also requires this PR to be live on Firebase (which it currently is): https://github.com/concord-consortium/reportservice/pull/3

**Comment by dougmartin** [comment]
NOTE: I need to add SequenceRuns to this.

**Comment by scytacki** [comment]
Given the other PR: https://github.com/concord-consortium/lara/pull/417  Should we close out this PR?  Or is there something here that isn't covered by #417 ?

**Comment by knowuh** [comment]
I will close this one, because #417 has is a super-set of this.

**Pull request closed without merging**
