### PR TITLE
WIP: 179598042 - Start on student side bar

### PR DESCRIPTION
**Pull request by knowuh**
# Summary:
Page Settings: Page Sidebar for Students
This PR enables editing Page Sidebar in the new-sections LARA authoring interface.

# Feature Story:

- Author checks the "Page has student sidebar menu" from the page settings menu.
- A preview of the student tip shows up on in the authoring interface.
- When the student tip is opened in the authoring interface it also displays "edit" options.

## TODO:
- WYSWIG editor (Fighting with TinyMCE ATM)
- Callbacks to update LARA DB entities (all client-side state ATM)

## Status:
Screen Shot 2022-06-29 at 5 56 27 PM
Screen Shot 2022-06-29 at 5 56 33 PM

[#179598042]
https://www.pivotaltracker.com/story/show/179598042

### CODE REVIEW

**Comment by knowuh** [comment]
@emcelroy -- This PR is just about ready. I decided to do the round-trip portal work in this PR too.

I am getting 2 test failures that look kinda strange an un-related.  

No urgency but I was wondering if you had seen ether of these failures before:

```
 1) GlossariesController GET index as an author assigns all glossaries as @glossaries
     Failure/Error: expect(assigns(:glossaries)).to eq([glossary, glossary2, glossary3])
       expected: [#<Glossary id: 14, name: "Nostrum aut quia eos illo aut.", json: "{}", user_id: 157, created_at: "20....", json: "{}", user_id: 158, created_at: "2022-07-01 22:03:46", updated_at: "2022-07-01 22:03:46">]
            got: [#<Glossary id: 16, name: "Et odio accusamus voluptas alias.", json: "{}", user_id: 158, created_at: ....", json: "{}", user_id: 156, created_at: "2022-07-01 22:03:45", updated_at: "2022-07-01 22:03:45">]
    
  2) Visiting all pages of a Sequence 'mode' query parameter handling not as a teacher... We should NOT see 'teacher-edition' in the url
     Failure/Error: click_link(activity.name)
     Capybara::ElementNotFound:
       Unable to find link "Consequatur voluptates temporibus quia doloremque "
```

**Comment by knowuh** [comment]
@emcelroy :  I merged upstream new-sections changes into this branch and the test are fixed now.

There are a lot of changes, but the majority of the changes are from pulling in the side bar widget from the Activity Player.

**Review by emcelroy — COMMENTED** [review]
This looks good except that when I test it out locally, the "Page has a student sidebar menu" isn't changing after I check or uncheck the box and click the Save & Close button.

I tried this both on a page that had an existing sidebar, and on a page that did not have a sidebar. In each case, the checkbox would never actually change. For the page with an existing sidebar, the sidebar always remained visible. For the page without an existing sidebar, a sidebar would never appear.

Is that working for you, @knowuh?

**Review by emcelroy — APPROVED** [review]
I got my local LARA running in a more stable fashion and checkbox changes are now being saved.

So this looks great 👍

**Pull request merged**
