### PR TITLE
Preview buttons per page on Activity Settings should respect runtime

### PR DESCRIPTION
**Pull request by emcelroy**
PT Story https://www.pivotaltracker.com/story/show/180461200

[#180461200]

### CODE REVIEW

**Comment by scytacki** [comment]
I've add @knowuh to this, so I can work on some other stuff.

**Comment by emcelroy** [comment]
@knowuh I just noticed a little mistake I made and that it'd be good to add a little more test coverage. I'm going to try to get to that momentarily. Will let you know when I've updated things.

**Comment by emcelroy** [comment]
@knowuh I'm done making changes. This is ready for review.

**Review by knowuh — APPROVED** [review]
Looks Good, 

Thank you Ethan

**Pull request merged**
