### PR TITLE
In standard authoring show which interactive a LabBook belongs to

### PR DESCRIPTION
**Pull request by knowuh**
This should complete [#97734786]

Update Labbook forms & tests

https://www.pivotaltracker.com/story/show/97734786

### CODE REVIEW

**Comment by knowuh** [comment]
@dougmartin when you get a chance.

**Comment by dougmartin** [comment]
This looks good to me but I think someone with deeper Rails experience should look at it.  @scytacki ?

**Comment by scytacki** [comment]
I think the labbook author should be able to select hidden interactives. 
Here is the scenario:
- an admin loads a ITSI activity in standard authoring mode
- they open a page that has two labbooks and to interactives
- one interactive is hidden
- and their are two labbooks on the page one for each interactive.
- the admin goes to edit one of the labbooks but they choose the one pointing to the hidden interactive
- the admin forgets and hits save instead of cancel
- now this labbook will be pointing at the wrong interactive.

Because of this scenario I think it is safer to allow the author to select even the interactives that are hidden on the page. You could put some text "(hidden)" in the interactive label, to make that more clear to author.

Other than this, the code looks good to me.

**Comment by knowuh** [comment]
@scytacki I added your suggestions, enabling an author to select a hidden interactive for the labbook.  Also provided a warning when an author has specified a snapshot labbook and the interactive isn't visible.

**Comment by scytacki** [comment]
:+1:

**Pull request merged**
