### PR TITLE
this fixes an issue with the app not being able to access the lara test database

### PR DESCRIPTION
**Pull request by scytacki**
This wasn't necessary for @pjanik, but when I tried to start up lara I was seeing errors.

### CODE REVIEW

**Comment by pjanik** [comment]
Honestly, I don't really understand that. A few lines below, in DB container, we specify master/master again. `docker/dev/run_spec.sh` exports root/xyzzy explicitly. There are a few other places where user/password is defined too. 😉 

I've tried that change locally, rebuild my app container, and everything still works. So, I'm fine with merging, but I can't say I'm following what's going on. 😉

**Comment by scytacki** [comment]
I didn't see that `docker/dev/run_spec.sh` configuring this itself.  I'm now pretture sure the error I was seeing was actually harmless.  It believe it was due to this line: 
https://github.com/concord-consortium/lara/blob/master/docker/dev/run.sh#L30 
I removed the duplicate references to usernames an passwords that aren't needed now.

Also I removed the comments that explain why using the root user is a required. 
Basically the DB docker container has some automatic configuration code. It looked at the DB
MYSQL_DATABASE, MYSQL_PASSWORD, and MYSQL_USER environment variables and creates a database if it doesn't exist. and then creates a user that only has access to that database.

By using the root user and password in docker-compose it simplifies things.

@pjanik can you check one more time that these new changes aren't breaking anything for you?

**Comment by scytacki** [comment]
I'm going to go a head and merge this in because I'm pretty sure it is safe.

**Comment by pjanik** [comment]
@scytacki, sorry, somehow I missed that on Friday. It works fine and simpler better now, thanks.

**Pull request merged**
