### PR TITLE
Fixed publish header in sequence edit broken by new react publishing details component

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by scytacki** [comment]
Can you update the naming here? It seems the ITSIAuthoring::PublicationDetails is no longer specific to ITSIAuthoring, and it isn't specific to working with activities.  Perhaps `publishable` instead of `activity` would work. That is just based on a quick skim so perhaps I'm missing some context.

**Comment by dougmartin** [comment]
Sure - updating now.

**Comment by dougmartin** [comment]
@scytacki I've moved the service out of itsi_authoring into the root of the services folder.

**Comment by scytacki** [comment]
:+1:

**Pull request merged**
