### PR TITLE
Add authorization to score_mapping_controller

### PR DESCRIPTION
**Pull request by pjanik**
[#120788853]

### CODE REVIEW

**Comment by scytacki** [comment]
@pjanik you probably can just add a `load_and_authorize_resource` to the top of the controller and remove the individual `authorize!` calls.  You can then also get rid of the `@score_mapping = CRater::ScoreMapping.find(params[:id])` statements.

**Comment by pjanik** [comment]
Thanks. I've tried `load_and_authorize_resource`, but it's not really working with the way how parameters are handled when new score mapping is created. So, I've used just `authorize_resource`.

**Comment by scytacki** [comment]
Unfortunately authorize_resource is probably not doing what you expect. If the `@score_mapping` variable is not set before authorize_resource runs, then it will just try to authorize `ScoreMapping`.  This works because admins have the ability `can :manage, :all`. Which means it doesn't mater what the resource or action is admins can do it.

If the only problem is in the create method, then you can do:
`load_and_authorize_resource :except => :create`

Then you can manually use the authorize method in the create method. Something like:
`authorize :create, ScoreMapping`

This approach has the advantage of allow use to use more fine grained abilities specific to instances later on without modifying the controller.

**Comment by scytacki** [comment]
I think this would also do the same thing:
```
load_and_authorize_resource
skip_load_resource :only => :create
```

**Comment by pjanik** [comment]
> Unfortunately authorize_resource is probably not doing what you expect. If the @score_mapping variable is not set before authorize_resource runs, then it will just try to authorize ScoreMapping. 

Actually, it was intentional. I was assuming that only admins can modify ScoreMappings and we don't really need to check anything specific to given instance, e.g. an owner. I didn't update abilities file anyway.

> This approach has the advantage of allowing us to use more fine grained abilities later without modifying the controller.

Agree, that's the main difference. I can't see an use case for more specific permissions in this case, but well, it won't hurt to follow this pattern. I'll do it.

**Comment by pjanik** [comment]
Done, thanks.

**Comment by scytacki** [comment]
👍

**Pull request merged**
