### PR TITLE
Change URLS  for Has Dashboard C-Rater reports to /api/*

### PR DESCRIPTION
**Pull request by knowuh**
Put all the Dashboard report endpoints in /api/v1/ 

This is the LARA side of https://github.com/concord-consortium/HASDashboard/pull/23/

https://www.pivotaltracker.com/story/show/121491615

### CODE REVIEW

**Comment by knowuh** [comment]
I will have a look at the failing `question_trackers` tests in a few.  Not sure how its related.

**Comment by knowuh** [comment]
@scytacki  would you care to give this a quick glance?   If not I can hit up some other people. Its small, mostly routing changes.

**Comment by scytacki** [comment]
Did you take a look at the result of `request.params.to_query`? 

I assume the intention is to just include the query params from the original request. I wonder though if rails or rake injects more things into the requests.params that we don't really want to be in the redirect.

**Comment by knowuh** [comment]
@scytacki  simplified in a037320

**Comment by scytacki** [comment]
👍 I'd merge this, but we are still trying to get out the 1.10.0 release. So I'd like to hold off on merging and updating staging until that release is done.

**Pull request merged**
