### PR TITLE
Interactive API: add API that lets interactives watch linked interactive state

### PR DESCRIPTION
**Pull request by pjanik**
Naming follows other add/remove<...>Listener functions exported by API (and actually used mainly by hooks).

`client.removeListener` doesn't look great anymore, but not sure how to extend it nicely and don't break backward compatibility.

[#174286292]

### CODE REVIEW

**Comment by scytacki** [comment]
This now has conflicts, probably because of the version number in the documentation.

**Review by scytacki — APPROVED** [review]
Looks good to me.

**Comment by scytacki** [comment]
@pjanik once the conflicts are resolved feel free to merge. 

And if you happen to be inspired to remove the version numbers from the documentation files (so we don't have conflicts and and so many changed files in PRs), that would be awesome.

**Comment by pjanik** [comment]
> And if you happen to be inspired to remove the version numbers from the documentation files (so we don't have conflicts and and so many changed files in PRs), that would be awesome.

Right, it was annoying. I just removed it.

**Pull request merged**
